name: Release

on:
  push:
    tags:
      - "v*"   # only run with version tags, e.g. git tag v0.0.1

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: ${{ !github.event.act }} # skip during local actions testing
    runs-on: ubuntu-latest
    steps:
      - name: Release to homebrew
        run: echo "homebrew"


# TODO: add release steps to package managers

